### ISSUE TITLE
Omni-c_qc.bash

### ISSUE THREAD

**Issue by marco91sol** [dovetail-genomics/dovetail_tools#18]
To whom it may concern, I'm running the script Omni-c_qc.bash. It gives me the attached error during bwa mem command step. 

How can I solve it?

Thanks for the support!

![image](https://user-images.githubusercontent.com/42739946/96010737-6f210f00-0e42-11eb-993a-1f727cdf1ced.png)

**Comment by datboncan** [comment]
Hello @marco91sol. By any chance, did you find any solution to address this? I'm also getting the same error. Thanks!

**Comment by datboncan** [comment]
The scripts works fine with shallow sequencing data (~1M read pairs), but the process is interrupted with a "Write Error" for deep sequencing data. My hunch is that redirecting a hefty amount of data from one step to another causes the issue.  I somehow managed to address this problem by breaking down the piped process into discrete steps (removing most pipes for stdin/stdout redirection) in the bash script particularly steps involving pairtools and by additing the flag/argument "--temp-dir=./" to "pairtools sort --tmp-dir=./ [OPTIONS] <infile>" as suggested in the following issue https://github.com/open2c/pairtools/issues/84. I haven't tried though if specifying this flag in the whole piped process will work.

**Comment by marco91sol** [comment]
sorry, if I just answer you now...I solved the issue with the same trick using --temp-dir=./ using in the "pairtools sort "
