### ISSUE TITLE
HiChIP QC  run Error

### ISSUE THREAD

**Issue by ValdemarP267** [dovetail-genomics/dovetail_tools#19]
To whom it may concern
Running the command as described. 
After [M::mem_process_seqs] i get

[bam-sort-core] merging from 20 files and 4 in-memory blocks. . .
ERROR:  too many defects in the approximation, consider running in defect mode

This follows with messages having issues opening files that do not exist due to above Error.

What can I do to solve this

Best,
Valdemar

**Comment by mlkhawand** [comment]
Valdemar, I will go ahead and close the issue here as we have been discussing the analysis via email (support@dovetail-genomics.com).
