### ISSUE TITLE
Omni-c_qc.bash

### ISSUE THREAD

**Issue by Luma-1994** [dovetail-genomics/dovetail_tools#20]
Hi, I'm running the script Omni-c_qc.bash. It gives me the attached error during bwa mem command step.

How can I solve it?

Thanks for the support!
slurmstepd: error: detected 1 oom-kill event in step 983019.batch cgroup.
slurmstepd: error: get_exit_code task 0 died by signal

**Comment by vatese** [comment]
Your slurm job is getting killed for exceeding the memory you requested. Not an issue with dovetail_tools.

**Comment by Luma-1994** [comment]
Thank you so much

**Comment by mlkhawand** [comment]
I hope having sufficient memory resolved the issue. If the issue persists, please reach out to us at support@dovetail-genomics.com.
