### ISSUE TITLE
omni-c_qc.bash failed 

### ISSUE THREAD

**Issue by CeciliaDeng** [dovetail-genomics/dovetail_tools#22]
Hi,

I tried to QC my huge amount of Omni-C data (about 500 million pairs of reads) using command:
`omni-c_qc.bash $REFindex $R1 $R2 $workDir/OmniC_QC $sample $thread`

It had executed for quite a while, processed a small portion of the reads, then failed with:

> [M::mem_process_seqs] Processed 749768 reads in 182.504 CPU sec, 18.485 real sec
ERROR:  Library expected to saturate in doubling of size, unable to extrapolate
Traceback (most recent call last):
  File "/workspace/hraaxt/Tools/dovetail_tools/get_qc.py", line 23, in <module>
    percent_unmapped = round(unmapped_reads*100.0/total_reads,2)
ZeroDivisionError: float division by zero

Help, please? The total reads should not be 0. How to fix it and get the QC going? 

Thank you.

**Comment by mlkhawand** [comment]
Addressed via email.
