### ISSUE TITLE
Implement regression test for QC script

### ISSUE THREAD

**Issue by jared-dtg** [dovetail-genomics/dovetail_tools#5]
Title pretty much says it all. Assigning to me for now.

One good regression data set would be: `s3://dtg-jared/lisasBug/*.gz`

- [ ] Choose a systematic place to host regression input datasets
- [ ] Write a script to diff outputs and report 👍 or 👎

cc @steve-dtg

**Comment by steve-dtg** [comment]
For the first checkbox, what do you like best from -
1. s3://doveregression/<DATE>/
2. s3://doveseq/regression
3. s3://doveargo/regression
4. Something else

**Comment by steve-dtg** [comment]
Also, is `s3://dtg-jared/lisasBug/*.gz` meant to be aligned to HG38?
