### ISSUE TITLE
Extend simple QC with simple HiChIP report

### ISSUE THREAD

**Issue by jared-dtg** [dovetail-genomics/dovetail_tools#8]
Add a new script that compute HiChIP stats:

### Input: 
1. BAM file (as aligned by `omnic_qc.sh`)
2. ChIP peaks in BED format
3. Reference genome FASTA

### Output
1. Valid read pairs
2. Valid Read pairs in peaks
3. Valid read pairs in (500, 1000, 2000, 5000)bp around peaks, absolute count and fraction of Valid
4. SNR (mean coverage within or near peaks / mean coverage outside peaks)

**Comment by dtg-jayghurye** [comment]
Done!

**Comment by jared-dtg** [comment]
Yay! Super fast. How're we gonna test it? I'm thinking run all of the HiChIP data to date through it and examine the results? 

cc @mblanche 

ps: probably should have done a PR instead of pushing straight to master -- makes it a bit harder to see what all was changed. no biggie though!
