### ISSUE TITLE
SNPs & Phasing

### ISSUE THREAD

**Issue by jared-dtg** [dovetail-genomics/dovetail_tools#9]
This is relevant to making Illumina happy

Add two scripts to this repo:

1. GATK UnifiedGenotyper for SNP calling
2. HAPCUT2 for phasing

Test on GM12878. 

Write a README that describes how to align, call SNPs, and Phase using these scripts, with links to the publicly available GM12878 data (input FASTQ's and BAMs and output VCFs). Also GIAB VCF and high confidence BED files.

@dtg-jayghurye cc @mlkhawand @cpadillla1331

**Comment by dtg-jayghurye** [comment]
The results are ready for GM12878 data with the new OmniC library (LM979). 

For SNP calling with UnifiedGenotyper and filtering, the sensitivity is 0.98 and specificity is 0.992.

Overall, the switch error is 0.015 and total phased SNVs are 1,712,078. If you are interested in detailed phasing results, here's an excel sheet. 

[NA12878_hapcut.xlsx](https://github.com/dovetail-genomics/omni-c_qc/files/4587971/NA12878_hapcut.xlsx)

I have all the raw and processed which I will upload to s3 and that can be shared.

**Comment by dtg-jayghurye** [comment]
VCF file with phase errors annotated is located here: http://dtgb.io/ebs/jayg/NA12878/na12878.phased.errorannotated.VCF.gz

**Comment by jared-dtg** [comment]
And the bam is here: http://dtgb.io/ebs/jayg/NA12878/poolA.bam

**Comment by mlkhawand** [comment]
Confirmed: LM979 library, used for All in One application note, was prepared following the most recent protocol (dual crosslinker).

**Comment by dtg-jayghurye** [comment]
@jared-dtg 
If you just restrict the SNPs that intersect with GIAB call set, we phase 1,693,563 SNPs at 0.013 switch error. Not very significant improvement compared to the non-filtered set.

The updated stats file is here: 
[NA12878_hapcut.xlsx](https://github.com/dovetail-genomics/omni-c_qc/files/4593626/NA12878_hapcut.xlsx)

**Comment by dtg-jayghurye** [comment]
Phasing outputs are up on s3 here: s3://dovetail-public/gm12878_phasing_data/
